{
  "id": "CVE-2019-15032",
  "published": "2019-09-19T17:15:00",
  "modified": "2023-10-10T12:29:05.516898",
  "details": "Pydio 6.0.8 mishandles error reporting when a directory allows unauthenticated uploads, and the remote-upload option is used with the http://localhost:22 URL. The attacker can obtain sensitive information such as the name of the user who created that directory and other internal server information.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
    }
  ],
  "repo_url": "https://github.com/pydio/pydio-core",
  "cwes": [],
  "commits": [
    "2dc263a711352a491b3d2d66a01537d6a7975425"
  ]
}
