{
  "id": "CVE-2019-12903",
  "published": "2019-06-20T00:15:10",
  "modified": "2023-11-29T07:01:40.407950",
  "details": "Pydio Cells before 1.5.0, when supplied with a Name field in an unexpected Unicode format, fails to handle this and includes the database column/table name as pert of the error message, exposing sensitive information.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N"
    }
  ],
  "repo_url": "https://github.com/pydio/cells",
  "cwes": [],
  "commits": [
    "a99933a3b75568ec6721e61053377ee8e88d438b"
  ]
}
