{
  "id": "CVE-2024-0397",
  "published": "2024-06-17T16:15:10",
  "modified": "2024-08-01T05:08:25.473562",
  "details": "A defect was discovered in the Python \u201cssl\u201d module where there is a memory\nrace condition with the ssl.SSLContext methods \u201ccert_store_stats()\u201d and\n\u201cget_ca_certs()\u201d. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
  "repo_url": "https://github.com/python/cpython",
  "cwes": [],
  "commits": [
    "1f2e3088f3c097b5bde69bbd63dfcd0852d31984",
    "3a833f748fc629d25a5af3faeef91447f4709804",
    "e3201094af2af2a9958333bd1cb212253941d644",
    "f992a60014b7ca83de038fc64572a63f4eb39c74"
  ]
}
