{
  "id": "CVE-2023-29824",
  "published": "2023-07-06T21:15:09",
  "modified": "2025-09-24T12:04:48.750339",
  "details": "A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "repo_url": "https://github.com/scipy/scipy",
  "cwes": [],
  "commits": [
    "7f208fa57f6470e2c428b91bbfc38ed86a7d5269"
  ]
}
