{
  "id": "CVE-2024-38875",
  "published": "2024-07-10T05:15:12",
  "modified": "2025-09-24T12:30:26.037662",
  "details": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
  "repo_url": "https://github.com/django/django",
  "cwes": [],
  "commits": [
    "3bf46e2e023904c825728267f3131c42f02ce696"
  ]
}
