{
  "id": "CVE-2021-46823",
  "published": "2022-06-18T16:15:08",
  "modified": "2023-11-29T09:07:31.610582",
  "details": "python-ldap before 3.4.0 is vulnerable to a denial of service when ldap.schema is used for untrusted schema definitions, because of a regular expression denial of service (ReDoS) flaw in the LDAP schema parser. By sending crafted regex input, a remote authenticated attacker could exploit this vulnerability to cause a denial of service condition.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "repo_url": "https://github.com/python-ldap/python-ldap",
  "cwes": [],
  "commits": [
    "e885b621562a3c987934be3fba3873d21026bf5c"
  ]
}
